//
// Created by Okada, Takahiro on 2018/04/14.
//

#ifndef MOBILITYHACKATHON_MOBILITYSTATUS_H
#define MOBILITYHACKATHON_MOBILITYSTATUS_H

typedef enum CAR_STATUS {
    DISCONNECTED,
    LOW_POWER,
    STANDBY,
    RESERVED,
    IN_USE
} eSTATUS;


#endif //MOBILITYHACKATHON_MOBILITYSTATUS_H
